/**
 * Backend API client. Re-exports from core, workflows, billing, settings, deployments.
 * Import from @/lib/api for all API functions.
 */

export {
  getApiBase,
  getGatewayOrigin,
  getDocsUrl,
  setAuthHeaderProvider,
  setOn401Callback,
  isAbortError,
  getErrorMessage,
  handleApiError,
  isAuthError,
  isCreditsError,
  normalizeApiError,
  reportApiError,
  API_UNREACHABLE_MESSAGE,
  AUTH_ERROR_MESSAGE,
  BYOK_REQUEST_TIMEOUT_MS,
  type ApiErrorWithStatus,
  type NormalizeApiErrorOptions,
  type FetchJsonOptions,
  fetchJson,
  fetchJsonAuthed,
} from './core';

export {
  DEFAULT_NETWORK,
  getWorkflows,
  getWorkflow,
  getWorkflowStatus,
  getWorkflowContracts,
  getWorkflowDeployments,
  createWorkflow,
  submitClarification,
  cancelWorkflow,
  getAgentDiscussionStreamUrl,
  getWorkflowUiSchema,
  generateWorkflowUiSchema,
  exportUiApp,
  downloadExportedZip,
  getPresets,
  getPlatformTrackRecord,
  getBlueprints,
  getRun,
  getRunSteps,
  approveSpec,
  approveDeploy,
  getNetworks,
  getStablecoins,
  testNetworkRpc,
  createQuickDemo,
  createDebugSandbox,
  getMetrics,
  getSecurityFindings,
  getDetailedHealth,
  listDomains,
  addDomain,
  getLogs,
  getLogServices,
  getLogHosts,
  getAgents,
  getTemplates,
  searchTemplates,
  contractRead,
  contractCall,
  type WorkflowResponse,
  type NetworkConfig,
  type PresetItem,
  type PlatformTrackRecord,
  type BlueprintItem,
  type RunDetail,
  type RunStep,
  type RunStepsResponse,
  type CreateWorkflowBody,
  type QuickDemoResponse,
  type DebugSandboxResponse,
  type SecurityFinding,
  type DomainRecord,
  type LogEntry,
  type LogsFilters,
  type LogsResponse,
  type AgentStatus,
  type AgentsResponse,
  type TemplateItem,
  type ClarificationEntry,
  type ClarifyResponse,
  type ExportUiAppResponse,
  type Metrics,
} from './workflows';

export {
  getPaymentHistory,
  getPaymentSummary,
  getSpendingControlWithBudget,
  patchSpendingControl,
  getCreditsBalance,
  topUpCredits,
  topUpCreditsWithTx,
  getPricingPlans,
  getPricingResources,
  getPricingUsage,
  type PaymentHistoryItem,
  type PaymentHistoryResponse,
  type PaymentSummary,
  type SpendingControlWithBudget,
  type SpendingControlPatchBody,
  type CreditsBalance,
  type CreditsTopUpBody,
  type PricingPlan,
  type PricingResource,
  type UsageSummary,
} from './billing';

export {
  getConfig,
  fetchConfigStrict,
  getConfiguredLLMProviders,
  requireLLMKeys,
  setLLMKeys,
  deleteLLMKeys,
  validateLLMKey,
  workspaceHeaders,
  LLM_KEYS_REQUIRED_MESSAGE,
  BYOK_SAVE_AGAIN_HINT,
  isByokStorageOrMigrationError,
  BYOK_RATE_LIMIT_MESSAGE,
  type IntegrationsStatus,
  type RuntimeConfig,
} from './settings';

export {
  prepareDeploymentTransaction,
  completeDeployment,
  type PrepareDeployParams,
} from './deployments';
