apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      containers:
        - name: api-gateway
          envFrom:
            - configMapRef:
                name: api-gateway-config
                optional: true
            - secretRef:
                name: api-gateway-secrets
                optional: false
