apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyperagent-production
resources:
  - ../../base
  - pdb.yaml
patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: hyperagent
  - path: hpa-orchestrator-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: orchestrator-hpa
  - path: hpa-gateway-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: api-gateway-hpa
  - path: orchestrator-secrets-required-patch.yaml
    target:
      kind: Deployment
      name: orchestrator
  - path: api-gateway-secrets-required-patch.yaml
    target:
      kind: Deployment
      name: api-gateway
labels:
  - includeSelectors: true
    pairs:
      environment: production
replicas:
  - name: api-gateway
    count: 2
  - name: orchestrator
    count: 2
