apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  template:
    spec:
      containers:
        - name: orchestrator
          envFrom:
            - configMapRef:
                name: orchestrator-config
                optional: true
            - secretRef:
                name: orchestrator-secrets
                optional: false
