from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field


class ArchitectureDesign(BaseModel):
    """
    Structured architecture specification for smart contract generation.
    Generated by DesignAgent before code synthesis.
    """
    contract_type: str = Field(..., description="High-level contract type (e.g., ERC20, ERC721, Custom, Subscription).")
    design_patterns: List[str] = Field([], description="Design patterns to apply (e.g., 'Factory', 'Proxy', 'Registry').")
    openzeppelin_modules: List[str] = Field([], description="OpenZeppelin modules to import and use (e.g., 'ReentrancyGuard', 'Ownable', 'Pausable').")
    contract_structure: Dict[str, Any] = Field({}, description="High-level structure: state variables, functions, events, modifiers.")
    dependencies: List[str] = Field([], description="External dependencies required (e.g., '@openzeppelin/contracts', '@chainlink/contracts').")
    security_considerations: List[str] = Field([], description="Security considerations and mitigations (e.g., 'reentrancy protection', 'access control').")
    gas_optimization_strategies: List[str] = Field([], description="Gas optimization strategies to apply (e.g., 'packed storage', 'custom errors').")
    limitations: List[str] = Field([], description="Known limitations or constraints of this architecture.")
    rationale: str = Field(..., description="Explanation of why this architecture was chosen for the given requirements.")
    estimated_complexity: str = Field("medium", description="Estimated complexity level: 'low', 'medium', 'high'.")
    compatibility_notes: Optional[str] = Field(None, description="Compatibility notes for target networks or versions.")

