# It handles the settings for the x402 service configuration for x402 payments (true or false) when this is true, the x402 service will be enabled and the x402 payments will be enabled
# when this is false, the x402 service will be disabled and the x402 payments will be disabled
apiVersion: hyperkitlabs.com/v1
kind: X402SettingsRegistry
metadata:
  name: x402-settings
  version: "1"
spec:
  settings:
    - id: x402-enabled
      name: X402 Enabled
      value: true
    - id: monitoring-enabled
      name: Monitoring Enabled
      value: false