# generated by datamodel-codegen:
#   filename:  hyperagent_state.schema.json
#   timestamp: 2026-01-19T09:22:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel


class Billing(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paymentRequired: bool
    priceUsd: float
    x402Enabled: bool


class Chains(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requested: list[str]
    selected: str


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filename: str
    id: str


class Contracts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Item]
    primaryId: str


class Execution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maxSteps: float
    step: float


class HyperAgentMetaV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    billing: Billing
    chains: Chains
    contracts: Contracts
    createdAt: str
    execution: Execution
    updatedAt: str
    version: Literal['v1']
    workflowId: str


class AuditResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    findings: list[str]
    passed: bool


class HyperAgentStatus(Enum):
    processing = 'processing'
    auditing = 'auditing'
    validating = 'validating'
    deploying = 'deploying'
    success = 'success'
    failed = 'failed'


class HyperAgentState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    auditResults: AuditResults
    contract: str
    deploymentAddress: str
    intent: str
    logs: list[str]
    meta: HyperAgentMetaV1
    status: HyperAgentStatus
    txHash: str


class Model(RootModel[HyperAgentState]):
    root: HyperAgentState
