apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hyperagent-staging

resources:
  - ../../base

replicas:
  - name: hyperagent-api
    count: 2

patches:
  - path: env-vars.yaml
  - path: replicas-patch.yaml

configMapGenerator:
  - name: hyperagent-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=staging

