apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hyperagent

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app: hyperagent
  version: v1.0.0

