#!/usr/bin/env python3
"""Export the canonical Spec Lock contract into schema-registry and api-contracts."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _load_contract_module():
    roma_root = _repo_root() / "services" / "roma-service"
    if str(roma_root) not in sys.path:
        sys.path.insert(0, str(roma_root))
    from spec_contract import SPEC_LOCK_EXAMPLE, spec_lock_json_schema

    return SPEC_LOCK_EXAMPLE, spec_lock_json_schema


def _render_ts_constant(name: str, value: object, *, header: str) -> str:
    return (
        f"{header}\n"
        f"export const {name} = {json.dumps(value, indent=2, ensure_ascii=False)} as const;\n"
    )


def _write(path: Path, text: str, *, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == text:
        return False
    if check:
        print(f"Out of date: {path}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated artifacts are out of date",
    )
    args = parser.parse_args()

    spec_lock_example, spec_lock_json_schema = _load_contract_module()
    schema = spec_lock_json_schema()

    root = _repo_root()
    registry_schema_path = (
        root / "packages" / "schema-registry" / "spec-contracts" / "v1" / "spec-lock.schema.json"
    )
    registry_fixture_path = (
        root / "packages" / "schema-registry" / "fixtures" / "spec-contracts" / "spec-lock-valid.json"
    )
    api_schema_json_path = (
        root / "packages" / "api-contracts" / "openapi" / "spec-lock.schema.json"
    )
    api_schema_ts_path = (
        root / "packages" / "api-contracts" / "src" / "generated" / "spec-lock.schema.ts"
    )

    schema_text = json.dumps(schema, indent=2, ensure_ascii=False) + "\n"
    fixture_text = json.dumps(spec_lock_example, indent=2, ensure_ascii=False) + "\n"
    ts_header = (
        "/**\n"
        " * Generated by scripts/schema/export_spec_contract.py from services/roma-service/spec_contract.py.\n"
        " * Do not edit manually.\n"
        " */\n"
    )
    ts_text = (
        _render_ts_constant("specLockJsonSchema", schema, header=ts_header)
        + "\n"
        + _render_ts_constant("specLockExample", spec_lock_example, header="")
    )

    changed = False
    changed |= _write(registry_schema_path, schema_text, check=args.check)
    changed |= _write(registry_fixture_path, fixture_text, check=args.check)
    changed |= _write(api_schema_json_path, schema_text, check=args.check)
    changed |= _write(api_schema_ts_path, ts_text, check=args.check)

    if args.check and changed:
        raise SystemExit(1)

    if not args.check:
        print("Exported Spec Lock schema to schema-registry and api-contracts")


if __name__ == "__main__":
    main()
