"""Markdown code block extraction utilities"""

import re
from typing import Optional


def strip_markdown_code_blocks(text: str) -> str:
    """
    Strip markdown code blocks from contract code

    Handles cases where code blocks weren't properly extracted earlier in the pipeline.
    Supports multiple formats:
    - ```solidity\n...code...\n```
    - ```\n...code...\n```
    - Unclosed code blocks

    Args:
        text: Contract code that may contain markdown formatting

    Returns:
        Clean Solidity code without markdown
    """
    if not text:
        return ""

    text = text.strip()

    # Try to extract from ```solidity code blocks (with closing ```)
    solidity_pattern = r"```solidity\s*\n(.*?)```"
    match = re.search(solidity_pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Try to extract from ```solidity code blocks (without closing ``` - unclosed block)
    unclosed_solidity_pattern = r"```solidity\s*\n(.*?)$"
    match = re.search(unclosed_solidity_pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Try to extract from generic ``` code blocks (with closing ```)
    generic_pattern = r"```[a-z]*\s*\n(.*?)```"
    match = re.search(generic_pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Try to extract from generic ``` code blocks (without closing ```)
    unclosed_generic_pattern = r"```[a-z]*\s*\n(.*?)$"
    match = re.search(unclosed_generic_pattern, text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # If code starts with ```, try to remove it manually
    if text.startswith("```"):
        first_newline = text.find("\n")
        if first_newline != -1:
            text = text[first_newline + 1 :]
            text = text.rstrip("`").strip()
            return text

    # If no code blocks found, return as-is (might be plain code)
    return text.strip()


def extract_solidity_code(text: str) -> str:
    """
    Extract Solidity code from markdown code blocks

    Alias for strip_markdown_code_blocks for backward compatibility
    """
    return strip_markdown_code_blocks(text)


def clean_template_placeholders(code: str) -> str:
    """
    Remove or replace template placeholders in generated code
    
    Template placeholders like {supply}, {name}, {symbol} are sometimes
    generated by LLMs but need to be replaced with actual values or removed.
    
    Args:
        code: Contract code that may contain template placeholders
        
    Returns:
        Clean code with placeholders replaced or removed
    """
    if not code:
        return code
    
    # Common template placeholders that should be replaced
    # Pattern: {variable_name} or {{variable_name}}
    placeholder_pattern = r'\{+\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}+'
    
    def replace_placeholder(match):
        var_name = match.group(1).lower()
        # Map common placeholders to reasonable defaults
        replacements = {
            'supply': '1000000',
            'initialsupply': '1000000',
            'name': '"Token"',
            'symbol': '"TKN"',
            'decimals': '18',
            'owner': 'msg.sender',
            'recipient': 'msg.sender',
            'amount': '0',
            'value': '0',
            'address': 'address(0)',
            'to': 'msg.sender',
            'from': 'msg.sender',
        }
        
        # Check if it's a known placeholder
        if var_name in replacements:
            return replacements[var_name]
        
        # For unknown placeholders, try to infer type from context
        # If it's in a string context, use empty string
        # If it's in a numeric context, use 0
        # Otherwise, use a reasonable default based on name
        if 'name' in var_name or 'title' in var_name:
            return '"Token"'
        elif 'symbol' in var_name or 'ticker' in var_name:
            return '"TKN"'
        elif 'supply' in var_name or 'amount' in var_name or 'value' in var_name or 'balance' in var_name:
            return '0'
        elif 'address' in var_name or 'addr' in var_name:
            return 'address(0)'
        elif 'bool' in var_name or 'flag' in var_name:
            return 'false'
        else:
            # Default: use 0 for numeric contexts, empty string for string contexts
            # This is a fallback - the prompt should prevent this
            return '0'
    
    # Replace all placeholders
    cleaned_code = re.sub(placeholder_pattern, replace_placeholder, code)
    
    # Log if we found any placeholders (for debugging)
    if '{' in code and code != cleaned_code:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning("Found and replaced template placeholders in generated code")
    
    return cleaned_code
